apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head><title>Frontend App - UAT</title></head>
    <body>
      <h1>Frontend App</h1>
      <p>Environment: <strong>uat</strong></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  labels:
    environment: uat
    stage: uat
  name: frontend-html
  namespace: kargo-lab-uat
