apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head><title>Frontend App - Test</title></head>
    <body>
      <h1>Frontend App</h1>
      <p>Environment: <strong>test</strong></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  labels:
    environment: test
    stage: test
  name: frontend-html
  namespace: kargo-lab-test
