apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head><title>Frontend App - Production</title></head>
    <body>
      <h1>Frontend App</h1>
      <p>Environment: <strong>production</strong></p>
    </body>
    </html>
kind: ConfigMap
metadata:
  labels:
    environment: prod
    stage: prod
  name: frontend-html
  namespace: kargo-lab-prod
