# OpenShift Route for Kargo API/UI
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kargo-api
  namespace: kargo
  labels:
    app.kubernetes.io/name: kargo-api
    app.kubernetes.io/part-of: kargo
spec:
  to:
    kind: Service
    name: kargo-api
    weight: 100
  port:
    targetPort: 443
  tls:
    termination: passthrough
  wildcardPolicy: None

