apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kargo-lab-uat
commonLabels:
  environment: uat
  stage: uat
resources:
- ../../base
replicas:
- name: frontend
  count: 2
patches:
- patch: |-
    - op: replace
      path: /data/index.html
      value: |
        <!DOCTYPE html>
        <html>
        <head><title>Frontend App - UAT</title></head>
        <body>
          <h1>Frontend App</h1>
          <p>Environment: <strong>uat</strong></p>
        </body>
        </html>
  target:
    kind: ConfigMap
    name: frontend-html
