apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Frontend App</title></head>
    <body>
      <h1>Frontend App</h1>
      <p>Environment: <strong>base</strong></p>
    </body>
    </html>
