apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: db-prod
namespace: kargo-lab-prod
resources:
  - ../../base
namePrefix: prod-
commonLabels:
  environment: prod
  stage: prod
commonAnnotations:
  kargo.akuity.io/stage: prod
patches:
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
    target:
      kind: PersistentVolumeClaim
      name: db-data
